"""add is_security_auditor to agents

Revision ID: 36233c2d6982
Revises: 283a489f4b56
Create Date: 2026-08-13 12:27:10.251350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36233c2d6982'
down_revision: Union[str, Sequence[str], None] = '283a489f4b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_security_auditor', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('agents', 'is_security_auditor', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_security_auditor')
    # ### end Alembic commands ###
