"""add notify_owner to agents

Revision ID: 534ff3c680a9
Revises: e14726f10dec
Create Date: 2026-08-13 11:50:07.378536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534ff3c680a9'
down_revision: Union[str, Sequence[str], None] = 'e14726f10dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('notify_owner', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('agents', 'notify_owner', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'notify_owner')
    # ### end Alembic commands ###
