"""add can_publish_instagram and pending_posts

Revision ID: 732872d1408a
Revises: 36233c2d6982
Create Date: 2026-08-13 18:22:37.489925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732872d1408a'
down_revision: Union[str, Sequence[str], None] = '36233c2d6982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_posts',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('instagram_container_id', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('can_publish_instagram', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('agents', 'can_publish_instagram', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'can_publish_instagram')
    op.drop_table('pending_posts')
    # ### end Alembic commands ###
