"""add handles_instagram_support to agents

Revision ID: 8d68649bb5ca
Revises: b49c7a86facf
Create Date: 2026-08-13 19:19:36.958092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d68649bb5ca'
down_revision: Union[str, Sequence[str], None] = 'b49c7a86facf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('handles_instagram_support', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('agents', 'handles_instagram_support', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'handles_instagram_support')
    # ### end Alembic commands ###
