"""add notified_messages to pending_posts

Revision ID: b49c7a86facf
Revises: 732872d1408a
Create Date: 2026-08-13 18:32:54.675253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49c7a86facf'
down_revision: Union[str, Sequence[str], None] = '732872d1408a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_posts', sa.Column('notified_messages', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_posts', 'notified_messages')
    # ### end Alembic commands ###
