"""allow shared telegram_chat_id across users

Revision ID: d96c13b0e9ff
Revises: b2e880e0dbe9
Create Date: 2026-08-13 12:10:20.578680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96c13b0e9ff'
down_revision: Union[str, Sequence[str], None] = 'b2e880e0dbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_telegram_chat_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_telegram_chat_id_key'), 'users', ['telegram_chat_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
